apiVersion: v1
kind: Service
metadata:
  name: solana-client-service
spec:
  selector:
    app: solana-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  externalTrafficPolicy: Local
  type: LoadBalancer
